name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    env:
      FORCE_COLOR: "1"
      UV_EXTRA_INDEX_URL: "https://download.pytorch.org/whl/cpu"
      UV_INDEX_STRATEGY: "unsafe-best-match"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          python-version: "3.10"
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml

      - name: Install Nox
        run: |
          uv pip install nox
          nox --version

      - name: Build package
        run: |
          nox -s build

      - name: Publish package on PyPI
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
