name: Tests

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "15 1 * * *" # every day at 01:15
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: ${{ matrix.python }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python: ["3.12", "3.11", "3.10"]

    env:
      FORCE_COLOR: "1"
      PRE_COMMIT_COLOR: "always"
      UV_EXTRA_INDEX_URL: "https://download.pytorch.org/whl/cpu"
      UV_INDEX_STRATEGY: "unsafe-best-match"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          python-version: ${{ matrix.python }}
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml

      - name: Install Nox
        run: |
          uv pip install nox
          nox --version

      - name: Lint with pre-commit and mypy
        run: |
          nox -v --session pre-commit mypy

      - name: Run tests
        run: |
          nox -v --session tests-${{ matrix.python }} -- --cov-report=xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        if: always()
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: coverage.xml
          fail_ci_if_error: true
